let keys = {
  "Squid Game": "oqxAJKy0ii4",
  "Money Heist": "Q59aCUnrFLQ",
  Hellbound: "LtdXK6yNFN0",
  Arcane: "fXmAurh012s",
  Lucifer: "ueMwVGBwqRo",
  "Money Heist: From Tokyo to Berlin": "Q59aCUnrFLQ",
  "Cobra Kai": "I3uX4uwrAaY",
  "Sex Education": "zmgYlYw7Uwk",
  Elite: "QNwhAdrdwp0",
  You: "xAN1ThhTWsE",
  "The Snitch Cartel: Origins": "WcPEICcYEdc&t",
  "My Name": "ZOl7iOrD31Q",
  "Narcos: Mexico": "hhZBDO0CKJo",
  "Sex/Life": "x580mowu5Gs",
  "Stranger Things": "b9EkMc79ZSU",
  "Jurassic World: Camp Cretaceous": "CRTIrK3Kku8",
  "Lost in Space": "fzmM0AB60QQ",
  "Venom: Let There Be Carnage": "FmWuCgJmxo",
  "The Last Duel": "mgygUwPJvYk",
  Hawkeye: "5VYb3B1ETlk",
  "No Time to Die": "N_gD9-Oa0fg",
  "Spider-Man: No Way Home": "ZYzbalQ6Lg8",
  Dune: "8g18jFHCLXk",
  "Shang-Chi and the Legend of the Ten Rings": "8YjFbMbfXaQ",
  "दिलवाले दुल्हनिया ले जायेंगे": "oIZ4U21DRlM",
  "The Shawshank Redemption": "6hB3S9bIaco",
  "The Godfather": "CWoQlDlyQj4",
  "Gabriel's Inferno Part II": "5g02v1oz5Y0",
  "Gabriel's Inferno Part III": "q56KnvgFcI8",
  "Schindler's List": "gG22XNhtnoY",
  "Nissene i bingen": "JQmz4TCk6Y4",
  "Natholdets julekalender": "JQmz4TCk6Y4",
  "The Simpsons": "HRV6tMR-SSs",
  "Marry Me, Marry You": "H2R8YucyHbY",
  "Without Breasts There Is No Paradise": "s3KM0PUk3LE",
  "Date a Live": "XxEWoejyqH8",
  "The Tudors": "WXNf9dxnQrM",
  "Sankarea: Undying Love": "Cz23IjHbUJY",
  "Trail of Lies": "9cq1lPPeMUY",
  "Maradona: Blessed Dream": "QgIiuVzRRr0",
  "Marvel Studios: Legends": "lWQF6F81kbY",
  "Welcome to Earth": "i0MTCXgil1M",
  "The Walking Dead: Origins": "sfAc2U20uyg",
  "": "lWQF6F81kbY",
};

export default keys;
